# -*- coding: utf-8 -*-
"""2-funcoes-numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IbIYS37_O3i5cP0pZdNouLdnspJUu-fa
"""

f = input()
a = float(input())
b = float(input())
c = float(input())

r = np.arange(a, b, c)

if f == 'seno':
  g = np.sin(r)
  print(*g, sep = ' ')

elif f == 'log2':
  g = np.log2(r)
  print(*g, sep = ' ')

elif f == 'log10':
  g = np.log10(r)
  print(*g, sep = ' ')

elif f == 'cosseno':
  g = np.cos(r)
  print(*g, sep = ' ')

else:
 print("Função desconhecida.")
