# -*- coding: utf-8 -*-
"""4-dados-metereologicos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QNKOgfN8v4CFQKlaI-AKeDGWmaMJoSkg
"""

import pandas as pd

entrada = input()
cidade = pd.read_csv(entrada)

if entrada == 'belem.csv':
  media = cidade["Velocidade do Vento {m/s}"].mean()
  densidademax = cidade["Densidade do ar {kg/m3}"].max()
  entalpiamin = cidade["Entalpia {BTU/LB}"].min()
  filtro_dir_media = cidade.query("Mes == 1 & Dia == 5")
  dir_media = filtro_dir_media["Direcao do Vento {graus}"].mean()
  ptodeorvlh = cidade[(cidade.iloc[:,5] >= 17) & (cidade.iloc[:,5] <= 18)]
  ptodeorvalho = len(ptodeorvlh)
  filtro_mediana = cidade[['Mes', 'Velocidade do Vento {m/s}']] #so aparece mes e velocidade do vento
  mediana = filtro_mediana.groupby("Mes")['Velocidade do Vento {m/s}'].median()
  raddireta = cidade.query("200 <= `Rad Direta Normal {Wh/m2}` and 0 < `Rad Difusa Horizontal {Wh/m2}` <= 100")["Rad Direta Normal {Wh/m2}"].count()
  raddiretafiltro = cidade.query("200 <= `Rad Direta Normal {Wh/m2}` and 0 < `Rad Difusa Horizontal {Wh/m2}` <= 100")
  raddireta = raddiretafiltro["Rad Direta Normal {Wh/m2}"].count()

  print('Media da velocidade do vento: %.2f'% media,'m/s')
  print('Maxima densidade do ar: %.2f'% densidademax, 'kg/m3')   
  print('Entalpia minima: %.2f'% entalpiamin, 'btu/lb')
  print('Media da direcao do vento no dia 5 do mes 1: %.2f'% dir_media, 'graus')
  print('Quantidade de registros de ponto de orvalho entre 17 e 18 graus Celsius:', ptodeorvalho)
  print(mediana)
  print('Rad Direta Normal maior ou igual a 200 e horizontal menor ou igual a 100 e maior que zero')
  print('Quantidade:',raddireta)
  print('10 primeiros:')
  print(raddiretafiltro[['Mes', 'Dia', 'Hora', 'Rad Direta {Wh/m2}']].head(10))

if entrada == 'saopaulo.csv':
  media = cidade["Velocidade do Vento {m/s}"].mean()
  densidademax = cidade["Densidade do ar {kg/m3}"].max()
  entalpiamin = cidade["Entalpia {BTU/LB}"].min()
  filtro_dir_media = cidade.query("Mes == 1 & Dia == 5")
  dir_media = filtro_dir_media["Direcao do Vento {graus}"].mean()
  ptodeorvlh = cidade[(cidade.iloc[:,5] >= 17) & (cidade.iloc[:,5] <= 18)]
  ptodeorvalho = len(ptodeorvlh)
  filtro_mediana = cidade[['Mes', 'Velocidade do Vento {m/s}']] #so aparece mes e velocidade do vento
  mediana = filtro_mediana.groupby("Mes")['Velocidade do Vento {m/s}'].median()
  raddireta = cidade.query("200 <= `Rad Direta Normal {Wh/m2}` and 0 < `Rad Difusa Horizontal {Wh/m2}` <= 100")["Rad Direta Normal {Wh/m2}"].count()
  raddiretafiltro = cidade.query("200 <= `Rad Direta Normal {Wh/m2}` and 0 < `Rad Difusa Horizontal {Wh/m2}` <= 100")
  raddireta = raddiretafiltro["Rad Direta Normal {Wh/m2}"].count()

  print('Media da velocidade do vento: %.2f'% media,'m/s')
  print('Maxima densidade do ar: %.2f'% densidademax, 'kg/m3')   
  print('Entalpia minima: %.2f'% entalpiamin, 'btu/lb')
  print('Media da direcao do vento no dia 5 do mes 1: %.2f'% dir_media, 'graus')
  print('Quantidade de registros de ponto de orvalho entre 17 e 18 graus Celsius:', ptodeorvalho)
  print(mediana)
  print('Rad Direta Normal maior ou igual a 200 e horizontal menor ou igual a 100 e maior que zero')
  print('Quantidade:',raddireta)
  print('10 primeiros:')
  print(raddiretafiltro[['Mes', 'Dia', 'Hora', 'Rad Direta {Wh/m2}']].head(10))

if entrada == 'florianopolis.csv':
  media = cidade["Velocidade do Vento {m/s}"].mean()
  densidademax = cidade["Densidade do ar {kg/m3}"].max()
  entalpiamin = cidade["Entalpia {BTU/LB}"].min()
  filtro_dir_media = cidade.query("Mes == 1 & Dia == 5")
  dir_media = filtro_dir_media["Direcao do Vento {graus}"].mean()
  ptodeorvlh = cidade[(cidade.iloc[:,5] >= 17) & (cidade.iloc[:,5] <= 18)]
  ptodeorvalho = len(ptodeorvlh)
  filtro_mediana = cidade[['Mes', 'Velocidade do Vento {m/s}']] #so aparece mes e velocidade do vento
  mediana = filtro_mediana.groupby("Mes")['Velocidade do Vento {m/s}'].median()
  raddireta = cidade.query("200 <= `Rad Direta Normal {Wh/m2}` and 0 < `Rad Difusa Horizontal {Wh/m2}` <= 100")["Rad Direta Normal {Wh/m2}"].count()
  raddiretafiltro = cidade.query("200 <= `Rad Direta Normal {Wh/m2}` and 0 < `Rad Difusa Horizontal {Wh/m2}` <= 100")
  raddireta = raddiretafiltro["Rad Direta Normal {Wh/m2}"].count()

  print('Media da velocidade do vento: %.2f'% media,'m/s')
  print('Maxima densidade do ar: %.2f'% densidademax, 'kg/m3')   
  print('Entalpia minima: %.2f'% entalpiamin, 'btu/lb')
  print('Media da direcao do vento no dia 5 do mes 1: %.2f'% dir_media, 'graus')
  print('Quantidade de registros de ponto de orvalho entre 17 e 18 graus Celsius:', ptodeorvalho)
  print(mediana)
  print('Rad Direta Normal maior ou igual a 200 e horizontal menor ou igual a 100 e maior que zero')
  print('Quantidade:',raddireta)
  print('10 primeiros:')
  print(raddiretafiltro[['Mes', 'Dia', 'Hora', 'Rad Direta {Wh/m2}']].head(10))

if entrada == 'riodejaneiro.csv':
  media = cidade["Velocidade do Vento {m/s}"].mean()
  densidademax = cidade["Densidade do ar {kg/m3}"].max()
  entalpiamin = cidade["Entalpia {BTU/LB}"].min()
  filtro_dir_media = cidade.query("Mes == 1 & Dia == 5")
  dir_media = filtro_dir_media["Direcao do Vento {graus}"].mean()
  ptodeorvlh = cidade[(cidade.iloc[:,5] >= 17) & (cidade.iloc[:,5] <= 18)]
  ptodeorvalho = len(ptodeorvlh)
  filtro_mediana = cidade[['Mes', 'Velocidade do Vento {m/s}']] #so aparece mes e velocidade do vento
  mediana = filtro_mediana.groupby("Mes")['Velocidade do Vento {m/s}'].median()
  raddireta = cidade.query("200 <= `Rad Direta Normal {Wh/m2}` and 0 < `Rad Difusa Horizontal {Wh/m2}` <= 100")["Rad Direta Normal {Wh/m2}"].count()
  raddiretafiltro = cidade.query("200 <= `Rad Direta Normal {Wh/m2}` and 0 < `Rad Difusa Horizontal {Wh/m2}` <= 100")
  raddireta = raddiretafiltro["Rad Direta Normal {Wh/m2}"].count()

  print('Media da velocidade do vento: %.2f'% media,'m/s')
  print('Maxima densidade do ar: %.2f'% densidademax, 'kg/m3')   
  print('Entalpia minima: %.2f'% entalpiamin, 'btu/lb')
  print('Media da direcao do vento no dia 5 do mes 1: %.2f'% dir_media, 'graus')
  print('Quantidade de registros de ponto de orvalho entre 17 e 18 graus Celsius:', ptodeorvalho)
  print(mediana)
  print('Rad Direta Normal maior ou igual a 200 e horizontal menor ou igual a 100 e maior que zero')
  print('Quantidade:',raddireta)
  print('10 primeiros:')
  print(raddiretafiltro[['Mes', 'Dia', 'Hora', 'Rad Direta {Wh/m2}']].head(10))

if entrada == 'vitoria.csv':
  media = cidade["Velocidade do Vento {m/s}"].mean()
  densidademax = cidade["Densidade do ar {kg/m3}"].max()
  entalpiamin = cidade["Entalpia {BTU/LB}"].min()
  filtro_dir_media = cidade.query("Mes == 1 & Dia == 5")
  dir_media = filtro_dir_media["Direcao do Vento {graus}"].mean()
  ptodeorvlh = cidade[(cidade.iloc[:,5] >= 17) & (cidade.iloc[:,5] <= 18)]
  ptodeorvalho = len(ptodeorvlh)
  filtro_mediana = cidade[['Mes', 'Velocidade do Vento {m/s}']] #so aparece mes e velocidade do vento
  mediana = filtro_mediana.groupby("Mes")['Velocidade do Vento {m/s}'].median()
  raddireta = cidade.query("200 <= `Rad Direta Normal {Wh/m2}` and 0 < `Rad Difusa Horizontal {Wh/m2}` <= 100")["Rad Direta Normal {Wh/m2}"].count()
  raddiretafiltro = cidade.query("200 <= `Rad Direta Normal {Wh/m2}` and 0 < `Rad Difusa Horizontal {Wh/m2}` <= 100")
  raddireta = raddiretafiltro["Rad Direta Normal {Wh/m2}"].count()

  print('Media da velocidade do vento: %.2f'% media,'m/s')
  print('Maxima densidade do ar: %.2f'% densidademax, 'kg/m3')   
  print('Entalpia minima: %.2f'% entalpiamin, 'btu/lb')
  print('Media da direcao do vento no dia 5 do mes 1: %.2f'% dir_media, 'graus')
  print('Quantidade de registros de ponto de orvalho entre 17 e 18 graus Celsius:', ptodeorvalho)
  print(mediana)
  print('Rad Direta Normal maior ou igual a 200 e horizontal menor ou igual a 100 e maior que zero')
  print('Quantidade:',raddireta)
  print('10 primeiros:')
  print(raddiretafiltro[['Mes', 'Dia', 'Hora', 'Rad Direta {Wh/m2}']].head(10))