# -*- coding: utf-8 -*-
"""5-dados-taxas-universitarias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nUhqxHgN6Qp802AZ_RH6w98gpOfLvefq
"""

import numpy as np
import pandas as pd

entrada = input()
valor = pd.read_csv('tuition_cost.csv')

if entrada.startswith("P") == True:
  lista = entrada.split(' ')
  coluna = lista[2]
  percentil_numero = lista[1]
  percentil = np.percentile(valor[coluna], q=int(percentil_numero))
  print('%.2f'%percentil)

elif entrada.startswith("M") == True:
  lista = entrada.split(' ')
  coluna = lista[1]
  media = valor[coluna].mean()
  desvio_padrao = valor[coluna].std()
  print('%.2f'% media, '%.2f'% desvio_padrao)

elif entrada.startswith("A") == True:
  lista = entrada.split(' ')
  coluna = lista[1]
  maximo = valor[coluna].max()
  minimo = valor[coluna].min()
  amp = maximo - minimo
  print('%.2f'% amp)
  
elif entrada.startswith('Q') == True:
  lista = entrada.split(' ')
  coluna = lista[3]
  xx = lista[1]
  yy = lista[2]
  total = len(valor.query(lista[3]+'>='+lista[1]+' and '+lista[3]+'<='+lista[2]))
  print(total)

else:
  print("Deu ruim")