# -*- coding: utf-8 -*-
"""5-dados-taxas-universitarias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nUhqxHgN6Qp802AZ_RH6w98gpOfLvefq
"""

# O objetivo deste trabalho é usar a biblioteca pandas e a biblioteca numpy do Python para analisar o mesmo arquivo CSV trabalhado na Unidade 5 com dados de taxas 
# universitárias (tuition). Neste trabalho, você criará um programa que lê um arquivo CSV e escreve na tela o dado pedido na entrada.

# O arquivo a ser lido se chama "tuition.csv" e poderá ser lido diretamente pelo comando read_csv da biblioteca pandas.

# Entrada do programa: uma linha com o comando a ser executado.

# Saída: o dado pedido de acordo com a entrada do programa.

# A linha de entrada é uma string que poderá seguir um dos seguintes padrões:

# "P XX COLUNA", em que XX é um valor inteiro e COLUNA é o nome do campo a ser considerado. Neste caso, seu programa deve escrever na tela o XXᵒ percentil dos valores
# cuja coluna tenha o nome COLUNA, arredondado para duas casas decimais;
# "M COLUNA", em que COLUNA é o nome da coluna a ser considerada. Neste caso, seu programa deve escrever na tela a média e o desvio padrão valores cuja coluna tenha o
# nome COLUNA. A média e o desvio padrão devem estar arredondados para duas casas decimais e separados por um espaço;
# "A COLUNA", em que COLUNA é o nome da coluna a ser considerada. Neste caso, seu programa deve escrever na tela a amplitude dos valores cuja coluna tenha o nome COLUNA,
# arredondada para duas casas decimais;
# "Q XX YY COLUNA", em que XX e YY são valores inteiros e COLUNA é o nome do campo a ser considerado. Neste caso, seu programa deve escrever na tela a quantidade de
# linhas para as quais o campo de nome COLUNA é maior ou igual a XX e menor ou igual a YY;
# Caso a primeira letra da entrada não seja "P", "M", "A", ou "Q", seu programa deve escrever "Deu ruim" na tela.
# Exemplo de entrada 1:
# P 25 in_state_tuition
# Exemplo de saída 1:
# 4890.00
# Exemplo de entrada 2:
# M in_state_tuition
# Exemplo de saída 2:
# 16491.29 14773.84
# Exemplo de entrada 3:
# A in_state_tuition
# Exemplo de saída 3:
# 59505.00
# Exemplo de entrada 4:
# Q 5000 10000 in_state_tuition
# Exemplo de saída 4:
# 709
# Exemplo de entrada 5:
# BCC
# Exemplo de saída 4:
# Deu ruim

import numpy as np
import pandas as pd

entrada = input()
valor = pd.read_csv('tuition_cost.csv')

if entrada.startswith("P") == True:
  lista = entrada.split(' ')
  coluna = lista[2]
  percentil_numero = lista[1]
  percentil = np.percentile(valor[coluna], q=int(percentil_numero))
  print('%.2f'%percentil)

elif entrada.startswith("M") == True:
  lista = entrada.split(' ')
  coluna = lista[1]
  media = valor[coluna].mean()
  desvio_padrao = valor[coluna].std()
  print('%.2f'% media, '%.2f'% desvio_padrao)

elif entrada.startswith("A") == True:
  lista = entrada.split(' ')
  coluna = lista[1]
  maximo = valor[coluna].max()
  minimo = valor[coluna].min()
  amp = maximo - minimo
  print('%.2f'% amp)
  
elif entrada.startswith('Q') == True:
  lista = entrada.split(' ')
  coluna = lista[3]
  xx = lista[1]
  yy = lista[2]
  total = len(valor.query(lista[3]+'>='+lista[1]+' and '+lista[3]+'<='+lista[2]))
  print(total)

else:
  print("Deu ruim")
