# -*- coding: utf-8 -*-
"""6-repeticoes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zn1bzC90rzzmALTL3scWn14eyyVP_2-A
"""

linhas = int(input())
somavalores = 0
lista = []

for i in range(0,linhas,1):
  valores = int(input())
  if valores >= 0:
    somavalores = valores + somavalores
    lista.append(valores)
invertida = list(reversed(lista))
print(*invertida, sep=" ")
print(somavalores)