# -*- coding: utf-8 -*-
"""7.1-grafico-seno-cosseno.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SDNVK-N5HX9HzREl1EW_mF6Ssme42eCU
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

#exercicio 1

x = np.arange(-10,10,0.01)
#cria o eixo x na escala de -10 a 10, em intervalos de 0,01
m = 2*np.sin(x/2)
#primeira funçao pedida
n = 2*np.sin(2*x)
#segunda funçao pedida
o = 1 + np.sin(2*x)
#terceira funçao pedida

plt.plot(x, m,'c')
#cria o grafico da primeira funçao e o c faz a linha tornar-se ciano
plt.plot(x,n,'b')
#cria o grafico da segunda funçao e o b faz a linha ficar azul
plt.plot(x,o,'r')
#cria o gráfico da terceira funçao e o r faz a linha ficar vermelho

plt.title("Funções")
#poe o nome 'funçoes' no grafico
plt.xlabel("Eixo x")    
#da nome ao eixo x
plt.ylabel("Eixo y")
#da nome ao eixo y
plt.grid()
#poe grade no grafico