# -*- coding: utf-8 -*-
"""7.3-media-final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kDX2eF3L3lbOiIQOqx7geUn8itfbWfZx
"""

# Escreva um programa que calcule a média da disciplina. Siga os seguintes passos:

# Peça para o usuário o número total de trabalhos e leia esse valor;
# Peça a nota de cada um dos trabalhos e leia;
# Peça a nota da prova e leia o valor;
# Calcule a média final como a média ponderada da média dos trabalhos (peso 6) e a nota da prova (peso 4);
# Escreva na tela a nota final numérica e também qual foi o conceito final do aluno, seguindo a conversão abaixo:
# Nota < 5, conceito F;
# 5,0 ≤ Nota < 6,0, conceito D;
# 6,0 ≤ Nota < 7,0, conceito C;
# 7,0 ≤ Nota < 8,5, conceito B;
# 8,5 ≤ Nota ≤ 10, conceito A.

#exercicio 3

listatrabalhos = []
#cria uma lista vazia pra armazenar o nome dos trabalhos que serão digitados a seguir

qnttrab = int(input())
#pede ao usuario a quantidade de trabalhos com que vamos trabalhar
for i in range(0, qnttrab):
  #o range limita-se a quantidade de trabalhos que o usuario digitou anteriormente
 trabalhos = int(input())
 #o usuario digita as notas dos trabalhos
 listatrabalhos.append(trabalhos)
 #adiciona as notas dos trabalhos na lista vazia criada inicialmente

prova = int(input())
#o usuario digita a nota da prova FORA DO LOOP
mediafinal = (prova* 6 + trabalhos *4) / 10
#fazemos uma media ponderada entre as notas das provas e dos trabalhos

if mediafinal < 5:
  print("Conceito F")
  #mostra conceito f para notas menores que cinco

elif mediafinal >= 5 and mediafinal < 6:
  print("Conceito D")
  #mostra conceito d para notas de cinco a seis

elif mediafinal >= 6 and mediafinal < 7:
  print("Conceito C")
  #mostra conceito c de notas entre seis e sete

elif mediafinal >= 7 and mediafinal < 8.5:
  print("Conceito B")
  #mostra conceito b para notas entre sete e oito e meio

elif mediafinal >= 8.5 and mediafinal <= 10:
  print("Conceito A")
  #mostra conceito a para notas maiores ou iguais a oito e meio
