# -*- coding: utf-8 -*-
"""7.4-mini-jogo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1icUNCiu5C-RVbv1XRye1ov6uvJ_D-trG
"""

#exercicio 4

import random as rd
pontosjog1 = 0
pontosjog2 = 0

#ambos os jogadores começam o jogo com zero pontos


while pontosjog1 != 3 and pontosjog2 != 3:
  a = int(input())
  b = rd.randint(1,6)
  d = rd.randint(1,6)
  #colocamos a mesma função da rolagem do dado para jogar pelo computador (jogador 2)

  if a != b: 
    if a == d:
     pontosjog1 = pontosjog1 + 1
     #um ponto ao jogador 1 se ele acerta a aposta


    elif b == d:
     pontosjog2 = pontosjog2 + 1
     #um ponto pro computador se ele acerta a aposta

  else:
    #essa condição se dá para que não haja empate
    if d == 1 or d == 2 or d == 3:
        pontosjog1 = pontosjog1 + 1
        #um ponto pro jogador 1 se o dado cair entre um e tres


    elif d == 4 or d == 5 or d == 6:
      pontosjog2 = pontosjog2 + 1
      #um ponto pro computador se o dado cair entre quatro e seis

  print('voce chutou', a)
  print('o jogador 2 chutou', b)
  print('o dado deu', d)
  print('voce tem', pontosjog1, 'pontos')
  print('o jogador 2 tem', pontosjog2, 'pontos')
  #os prints se encontram dentro do loop, irão mostrar o placar e as apostas enquanto o jogo não acabar

else:
  #fora das condiçoes do loop (caso algum dos jogadores atinja 3 pontos) 
  if pontosjog1 == 3:
   print('Parabéns, Jogador 1!')
#parabeniza-se o jogador 1 se ele atingir trêspontos primir
  else:
    print('Parabéns, Jogador 2!')